# Generated by Django 5.1.1 on 2024-09-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="item",
            old_name="create_by",
            new_name="created_by",
        ),
    ]
